### ISSUE TITLE
Crash on launch when paired with abnormals core

### ISSUE THREAD

**Issue by Wizelf402** [HalogenMods/Chlorine#17]
When both the Abnormals Core and Chlorine are installed, it results in a crash on launch, making the two mods completely incompatible.

[Logs.txt](https://github.com/HalogenMods/Chlorine/files/5983150/Logs.txt)

**Comment by Corvus20** [comment]
I am experience this issue as well.

**Comment by hanetzer** [comment]
Duplicate #10
