### ISSUE TITLE
Lines between blocks

### ISSUE THREAD

**Issue by Leclowndu93150** [HalogenMods/Chlorine#29]
### Expected Behavior
There should be no lines between blocks

### Actual Behavior
Lines between blocks

### Reproduction Steps
 

1. Install Chlorine
2. Enable Anti aliasing
3. Lines between blocks

### Attachments

![image](https://user-images.githubusercontent.com/73310949/114143867-87418a80-98c9-11eb-8f89-78142f7d9ee4.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [java 8 211]
- CPU: [i3-3110m]
- GPU: [intel hd 4000]

**Comment by Patchumz** [comment]
Disabling Compact Vertex Format fixes this.

**Comment by yezhiyi9670** [comment]
Check your graphic card settings. Turning off Anisotropic Filtering might help.

**Comment by Corvus20** [comment]
> Disabling Compact Vertex Format fixes this.

how does one disable this? I have been unable to find an option for it in the configs.

**Comment by Patchumz** [comment]
> 
> 
> > Disabling Compact Vertex Format fixes this.
> 
> how does one disable this? I have been unable to find an option for it in the configs.

I don't know what it's labeled as in the configs, but as translated in the options menu in game it says Compact Vertex Format.

![YoloMouse_2021-05-07_09-47-20](https://user-images.githubusercontent.com/1404291/117482614-79f3dc00-af19-11eb-8f69-2857c1d9c13b.png)

**Comment by Leclowndu93150** [comment]
ty
