### ISSUE TITLE
Immersive Engineering wires don't render.

### ISSUE THREAD

**Issue by Edulml** [HalogenMods/Chlorine#5]
### Expected Behavior
The wires are visible.

### Actual Behavior
The Immersive Engineering wires are invisible, I have tested this in all 3 renderer settings (2.0, 3.3, 4.3) and they stay invisible.

### Reproduction Steps
Simply use the Immersive Engineering wires normally and you'll notice they are missing. 

- Java Version: Adopt OpenJDK jre-8.0.252.09
- CPU: Intel i5 3330
- GPU: Zotac GTX750ti

**Comment by hanetzer** [comment]
Versions of every mod involved and screenshots, please :)

**Comment by malte0811** [comment]
If you need help from/changes on IE's side I'll be happy to help, either here or in Discord DMs (malte0811#3564).

Edit: The main problem is [this line](https://github.com/BluSunrize/ImmersiveEngineering/blob/1ac7ec92297642f70eb083027a7f92e7bc3fb913/src/main/java/blusunrize/immersiveengineering/client/models/connection/BakedConnectionModel.java#L174). The code is irrelevant in *most* cases now (it was used to make chunk culling issues look slightly less ugly), but for translucent connectors it stops the wire from rendering in both solid and translucent. Even with that changed there seem to be some issues, I'll look into it further from the IE side.

Edit2: Calling [this](https://github.com/MinecraftForge/MinecraftForge/blob/0d7f507f4e7337436e3208d5ba4054ef14895669/src/main/java/net/minecraftforge/client/ForgeHooksClient.java#L179-L182) in the relevant places in Chlorine should fix the wires not rendering at all, I still need to figure out why the colors didn't work when I tested it.

Edit3: I think I've fully fixed it now (from the Chlorine side), I'll make a PR with the changes later.
