### ISSUE TITLE
Chlorine seems to halt the loading process when coupled with modded 1.16.4

### ISSUE THREAD

**Issue by papuSpartan** [HalogenMods/Chlorine#8]
### Reproduction Steps
launch game
wait
it freezes

### Crash Report File
https://gist.github.com/papuSpartan/aca8ca501aebab166a9ad8f69a77d54d

### Additional Information
loading process freezes instead of crashing.
This was after removing multiple mods which suddenly claimed to have class-loading errors.

**Comment by hanetzer** [comment]
Probably a compat issue; it was never updated to >1.16.3 when this was filed. If you haven't already, give it a try with the new build on cf.
